tf_arsfest/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from views import *


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       
    url(r'^$', TemplateView.as_view(template_name='home.html')),                

    # Uncomment the admin/doc line below to enable admin documentation:
     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^(?P<year>\d\d\d)/new/$', register, name='add-participant'),
    url(r'^sponsor_logos/', list_sponsor_logos, name='list_sponsor_logos'),
    
    
)

# TODO: Add production collecting of files
urlpatterns += staticfiles_urlpatterns()

tf_arsfest/models.py
# --coding: UTF-8 --
from django.db import models
from referencenumber import viitenumeron_tarkiste

class Guest(models.Model):
    # Name
    name = models.CharField(max_length=90, verbose_name="Namn")
    
    # Email
    email = models.EmailField(verbose_name="E-post adress")
    
    # Phone
    phone = models.CharField(max_length=20, verbose_name="Telefonnummer")
    
    # Allergies
    allergies = models.CharField(max_length=180, verbose_name="Allergier/Dieter", blank=True)
    
    # Student or not
    type = models.ForeignKey('GuestType', verbose_name="Deltagartyp")

    # Sex
    SEX = (('M', 'Man'),('F', 'Kvinna'))
    sex = models.CharField(max_length=1, choices=SEX, verbose_name="Kön", blank=True)
    # Alkoholfri
    nonalcoholic = models.BooleanField(verbose_name="Alkoholfri", default=False)
    
    # Silliz
    silliz = models.BooleanField(verbose_name="Sillfrukost")
    
    event = models.ForeignKey('Event', verbose_name="Årsfest");
    
    def __unicode__(self):
        return self.name
    
        
class Registration(models.Model):
    
    # Vilken fest
    event = models.ForeignKey('Event', verbose_name="Årsfest");
    
    # Förening
    name = models.CharField(max_length=150, verbose_name="Förening/Post", blank=True, null=True)
    
    # Deltar i solenn-akt
    solennakt = models.BooleanField(verbose_name="Deltar i solenn akt", default=False)
    
    # Framför hälsning
    greeting = models.BooleanField(verbose_name="Vill framföra hälsning", default=False)
    
    # Gäst
    guest = models.OneToOneField(Guest, related_name="guest", unique=True)
    
    # Avec
    avec = models.OneToOneField(Guest, blank=True, null=True, related_name="avec", unique=True)
    
    # Övrigt
    misc = models.TextField(verbose_name="Övrigt", blank=True)
    
    # +1 boolean
    plusone = models.BooleanField(verbose_name="Lägg till person")
    
    # Avec boolean
    avecbutton = models.BooleanField(verbose_name="Avec")
    
    # Referensnummer till räkning
    reference_number = models.PositiveIntegerField(verbose_name="Referensnummer", blank=True, null=True, unique=True)
    
    # Summa på räkningen
    sum = models.FloatField(verbose_name="Summa", blank=True, null=True)
    
    def get_dictionary(self):
        
        data = {}
        
        registration = {}
        registration['org'] = self.name
        registration['solenn'] = "Ja" if self.solennakt else "Nej"
        registration['greeting'] = "Ja" if self.greeting else "Nej"
        registration['misc'] = self.misc
        data['registration'] = registration
        
        guest = {}
        guest['name'] = self.guest.name
        guest['email'] = self.guest.email
        guest['phone'] = self.guest.phone
        guest['allergies'] = self.guest.allergies
        guest['sex'] = self.guest.sex
        guest['type'] = unicode(self.guest.type)
        guest['nonalcoholic'] = "Ja" if self.guest.nonalcoholic else "Nej"
        guest['silliz'] = "Ja" if self.guest.silliz else "Nej"      
        data['guest'] = guest
        
        avec = {}
        if self.avec is not None:
            avec['name'] = self.avec.name
            avec['email'] = self.avec.email
            avec['phone'] = self.avec.phone
            avec['allergies'] = self.avec.allergies
            avec['sex'] = self.avec.sex
            avec['type'] = unicode(self.avec.type)
            avec['nonalcoholic'] = "Ja" if self.avec.nonalcoholic else "Nej"
            avec['silliz'] = "Ja" if self.avec.silliz else "Nej"
            data['avec'] = avec
            
        data['reference_number'] = self.reference_number
        data['sum'] = self.sum
        
        return data
    
    def save(self, *args, **kwargs):        
        self.sum = self.guest.type.price
        
        if self.avec is not None:
            self.sum += self.avec.type.price
            if self.avec.nonalcoholic and self.avec.type.price != 0:
                self.sum -= self.event.alcohol_price
            if self.avec.silliz:
                self.sum += self.event.silliz_price
            
            
        if self.guest.silliz:
            self.sum += self.event.silliz_price
            
        if self.guest.nonalcoholic and self.guest.type.price != 0:
            self.sum -= self.event.alcohol_price
        
        super(Registration, self).save(*args, **kwargs)
        
        if self.reference_number is None:
            pkey = "%d%d"%(self.event.year,self.pk)
            self.reference_number = "%d%d"%(int(pkey), viitenumeron_tarkiste(pkey))
            
        super(Registration, self).save(*args, **kwargs)
        
    
    
    
    def __unicode__(self):
        return "%s %s" % (self.name, self.guest.name)
    
class Event(models.Model):
    
    # Årsfest nr
    year = models.PositiveIntegerField(primary_key=True)
    
    # Date&Time
    date = models.DateTimeField()
    
    # Name
    name = models.CharField(max_length=120, verbose_name="Händelsens namn")
    
    # Platser
    places = models.PositiveIntegerField(verbose_name="Max antal gäster")
    
    # Anmälningen öppnar första gången
    round1_opens = models.DateTimeField()
    
    # Anmälningen stänger första gången
    round1_closes = models.DateTimeField()
    
    # Anmälningen öppnar andra gången
    round2_opens = models.DateTimeField()
    
    # Anmälningen stänger andra gången
    round2_closes = models.DateTimeField()
    
    # Beskrivning på anmälan
    registration_description = models.TextField(verbose_name="Beskrivning vid anmälan")    
    
    # Silliz pris
    silliz_price = models.PositiveIntegerField(verbose_name="Sillis pris")
    
    # Alkoholets pris
    alcohol_price = models.PositiveIntegerField(verbose_name="Hur mycket billigare är alkoholfritt?")
    
    def __unicode__(self):
        return self.name
    
class GuestType(models.Model):
    
    # Name of type
    name = models.CharField(max_length=50, verbose_name="Namn (t.ex. studerande)")
    
    # Price
    price = models.PositiveIntegerField(verbose_name="Pris")
    
    def __unicode__(self):
        return "%s (%de)" % (self.name, self.price)
    

tf_arsfest/forms.py
from django.forms import ModelForm, RadioSelect
from models import Registration, Guest


class RegistrationForm(ModelForm):
    class Meta:
        model = Registration
        exclude = ('guest', 'avec', 'event', 'reference_number', 'sum')
        
class GuestForm(ModelForm):
    class Meta:
        model = Guest
        exclude = ('event')
        
        
    

tf_arsfest/views.py
from django.template import RequestContext
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render_to_response, get_object_or_404
from forms import GuestForm, RegistrationForm
from models import Event, Guest, Registration
from django.utils import timezone
from django.template.loader import render_to_string

    
def register(request, year):
    
    event = get_object_or_404(Event, pk=year);
    
    places = event.places - len(Guest.objects.filter(event=event))
    
    
    now = timezone.now()
    if now < event.round1_opens or (now > event.round1_closes and now < event.round2_opens) or now > event.round2_closes or not places > 0:
        return render_to_response('registration_closed.html', {'event': event, 'places': places}, context_instance=RequestContext(request))
        
    
    # If posting a filled out form
    if request.POST:
        
        # Get the forms from the POST data
        registration_form = RegistrationForm(request.POST)
        guest_form = GuestForm(request.POST, prefix='guest')
        avec_form = GuestForm(request.POST, prefix='avec')
        
        # If the main guest form and registration specific info was correct
        if guest_form.is_valid() and registration_form.is_valid():
            
            registration = registration_form.save(commit=False)   
            
            # If there was an avec
            if registration.plusone:
                # If the avec was filled out correctly
                if avec_form.is_valid():
                    avec = avec_form.save(commit=False)
                    avec.event = event
                    avec.save()
                    registration.avec = avec
                else:
                    return render_to_response('registration_form.html', {'registration': registration_form,
                                                             'guest': guest_form,
                                                             'avec': avec_form,
                                                             'year': year,
                                                             'desc': event.registration_description}
                                  , context_instance=RequestContext(request))
            
            # All good, save                   
            guest = guest_form.save(commit=False)
            guest.event = event
            guest.save()
            registration.guest = guest                 
            registration.event = event
            registration.save()
            
            data = registration.get_dictionary()
            send_registration_email(data)
            return render_to_response('registration_done.html', {'year': year, 'data': data}, context_instance=RequestContext(request))
        
    # If not POST    
    else:
        registration = Registration()
        registration.event = event
        registration_form = RegistrationForm(instance=registration)
        guest_form = GuestForm(prefix='guest')
        avec_form = GuestForm(prefix='avec')
        
        if places <= 1:
            registration_form.fields['avecbutton'].widget.attrs['disabled'] = True

    
    # If forms not valid or not POST
    return render_to_response('registration_form.html', {'registration': registration_form,
                                                             'guest': guest_form,
                                                             'avec': avec_form,
                                                             'year': year,
                                                             'desc': event.registration_description}
                              , context_instance=RequestContext(request))
        
def send_registration_email(data):
         
    subject, from_email, to = 'Registrering mottagen', 'TF<arsk@teknolog.fi>', data['guest']['email']
    content = render_to_string('email.txt', {'data': data})
     
    msg = EmailMultiAlternatives(subject, content, from_email, [to])
    msg.send()


def list_sponsor_logos(request):
    #TODO:  Make the sponsorlogos so they are uploaded in admin interface.
    #       And make this to return all those logos to display on an info screen...    
    return render_to_response('sponsor_logos.html', context_instance=RequestContext(request))

tf_arsfest/templates/base.html
<!DOCTYPE html>
<html lang="sv">
<head>
	<meta charset="utf-8">
	<title>TF &Aring;rsfest</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- IE6-8 support of HTML elements -->
	<!--[if lt IE 9]>
	      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	    <![endif]-->

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

	<link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
	<link href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" rel="stylesheet">

	<link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">	

</head>

<body class="{% block body_classes %}{% endblock %}">

	{% block content %} {% endblock %}

	<h2>&nbsp;</h2>
	<h2>&nbsp;</h2>
	<h2>&nbsp;</h2>
	<footer>
		<p id="copyRightText">&copy; Logo design by Caro Line tmi</p>
	</footer>

	<script type="text/javascript"
		src="//platform.twitter.com/widgets.js"></script>
	<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
</body>
</html>

tf_arsfest/templates/home.html
{% extends 'base.html' %} {% block content %}
<div class="container">

	<div class="row">
		<div class="offset1 span5">
			<h1 class="welcome">Välkommen</h1>
		</div>
	</div>

	<div class="row">
		<div class="offset1 span5">
			{% block middle %}
			<p class="caps smallspacing">på Teknologföreningens 143:e  årsfest!</p>
			<p>Teknologföreningen firar sin 143:e årsfest lördagen
			den 21 mars 2015.</p>
			<p>
			Festligheterna inleds med solenn akt vid Design Factory (Betongblandargränden 5)
			på Aalto-universitetets campus i Otnäs, där det
			finns möjlighet att framföra hälsningar till nationen.
			Efter den solenna akten fortsätter festligheterna på Teknologföreningens nationshus	
			Urdsgjallar.</p>
			<p>
			Priset på supékortet är 80<span class="euro">€</span> för studerande 
			(65<span class="euro">€</span> alkoholfritt) och 100<span class="euro">€</span> 
			för graduerade (85<span class="euro">€</span> alkoholfritt).
			Sillfrukosten kostar 10<span class="euro">€</span> vid förköp, 
			12<span class="euro">€</span> vid dörren.</p>

			<p>Vi önskar alla gäster en trevlig och minnesrik fest!</p>
			<p>
			Anmälan öppnar 2 februari för inbjudna gäster och 20 februari för övriga.
			<a class="" href="/143/new/"><h2>Anmälan</h2></a>
				
			</p>
			{% endblock %}

		</div>
		<!--/span-->
		
		<div class="offset1 span3">
		<a href="/">
			<img src="{{ STATIC_URL }}img/143_noextra.png" alt="143" />
			</a>
		</div>

	</div> <!-- /row -->

	<div class="row">
		<div class="offset1 span5">
			<p class="caps heading">Kontaktuppgifter</p>
			<p>Ifall det finns något oklart angående arrangemangen besvarar årsfestmarskalkerna gärna dina frågor.</p>

			<p>Andreas Holm 044 277 0611 <br /> 
			Henrik Hillner 041 505 7004<br /></p>

			
			<p><a href="mailto:marskalker@teknolog.fi">marskalker@teknolog.fi</a></p>
			
			<p>
				Urdsgjallar<br /> Otsvängen 22<br /> 02150 Esbo
			</p>
		</div>
		
		<div class="offset1 span5">
			<p class="caps heading">Tidtabell</p>
			
			<table>
			<tr><td colspan="2"><h3 class="timetable">21 Mars 2015</h3></td></tr>
			
				<tr>
				<td>Solenn Akt</td><td>16:00</td><td>Design Factory,</br > Betongblandargränden 5C</td>
				</tr>
				
				<tr>
				<td>Cocktail</td><td>17:30</td><td>Urdsgjallar, Otsvängen 22</td>
				</tr>
				
				<tr>
				<td>Bankett</td><td>19:00</td><td>Urdsgjallar, Otsvängen 22</td>
				</tr>

				<tr><td colspan="2"><h3 class="timetable">22 Mars 2015</h3></td></tr>
			
				<tr><td>Sillfrukost</td><td>12:00</td><td>Urdsgjallar, Otsvängen 22</td></tr>
			</table>
			<p>
				<br /><a
					href="https://www.google.com/maps/d/viewer?mid=zaFxVrbCwvX0.kMudjIY3CB2w"
					target="_blank">Karta &raquo;</a>
			</p>
		
		</div> <!--/span-->

	</div> <!--/row-->
	<div class="row">
		<div class="offset1 span10">
			<div id="spons">
				<h2>&nbsp;</h2>
				<p class="caps heading">Sponsorer</p>
					<a href="http://www.thermoscientific.com/en/products/diagnostic-testing-products.html">
						<img src="{{ STATIC_URL }}festreklam/thermo14.jpg" alt="thermoscientific" />
					</a>
					<a href="http://aholatransport.com">
						<img src="{{ STATIC_URL }}festreklam/ahola14.png" alt="Ahola" />
					</a>
					<a href="http://attracs.com/">
						<img src="{{ STATIC_URL }}festreklam/attracs14.png" alt="Attracs" />
					</a>
					<a href="http://futurice.com/">
						<img src="{{ STATIC_URL }}festreklam/futurice.png" alt="futurice" />
					</a>
					<a href="http://tfif.fi/">
						<img src="{{ STATIC_URL }}festreklam/tfif14.png" alt="tfif" />
					</a>
					<a href="#">
						<img src="{{ STATIC_URL }}festreklam/LR14.jpg" alt="Lloyd's Register" />
					</a>
			</div>
		</div>
	</div> <!-- Sponsor reklam -->

</div> <!-- /container -->

{% endblock %}

tf_arsfest/templates/participant_form.html
{% extends 'base.html' %} {% block content %}
<div class="row-fluid">
	<div class="span9">

		<form action="/participant/new/" method="post">
			<table>
        		{{ formset }}
    		</table>
		</form>

	</div>
	<!--/span-->
</div>
<!--/row-->
{% endblock %}

tf_arsfest/templates/registration_closed.html
{% extends 'home.html' %}

{% block middle %}

		<div class="">
			<h1>Registreringen är inte öppen.</h1>

				<p>Anmälan för inbjudna börjar {{ event.round1_opens }} och slutar {{ event.round1_closes }}</p>
				<p>Allmänna anmälan börjar {{ event.round2_opens }} och slutar {{ event.round2_closes }}</p>
				<p>Det finns {{ places }} platser kvar.</p>
				<p><a class="caps" href="/">Tillbaka</a></p>
				<h2>&nbsp;</h2>
		</div>

{% endblock %}

tf_arsfest/templates/registration_done.html
{% extends 'home.html' %} 

{% block middle %}

			<h1>Registrerad</h1>

				<ul>
					<li>Förening: {{ data.registration.org }}</li>
					<li>Deltar i solenn akt:  {{ data.registration.solenn }}
					<li>Vill framgöra hälsning: {{ data.registration.greeting }}</li>
					<li>Övrigt: {{ data.registration.misc }}</li>
				</ul>
				<ul>
					<li>Namn: {{ data.guest.name }}</li>
					<li>Epost: {{ data.guest.email }}</li>
					<li>Telefon: {{ data.guest.phone }}</li>
					<li>Allergier/Diet: {{ data.guest.allergies }}</li>
					<li>Pris: {{ data.guest.type }}</li>
					<li>Alkoholfri:  {{ data.guest.nonalcoholic }}</li>
				</ul>
				
				{% if data.avec %}
				<ul>
					<li>Namn: {{ data.avec.name }}</li>
					<li>Epost: {{ data.avec.email }}</li>
					<li>Telefon: {{ data.avec.phone }}</li>
					<li>Allergier/Diet: {{ data.avec.allergies }}</li>
					<li>Pris: {{ data.avec.type }}</li>
					<li>Alkoholfri:  {{ data.avec.nonalcoholic }}</li>
				</ul>
				{% endif %}
				
				<ul>
					<li>Referensnummer: {{ data.reference_number }}</li>
					<li>Summa: {{ data.sum }}&euro;</li>
				</ul>

{% endblock %}

tf_arsfest/templates/registration_form.html
{% extends 'home.html' %}

{% block middle %}

		<p>{{ desc|safe }}</p>

		<form action="/{{ year }}/new/" method="post">
			{% csrf_token %}

				{{ guest.as_p }} {{ registration.as_p }}

				<div id="avec-table">{{ avec.as_p }}</div>
							
				<button type="submit" class="btn">Skicka</button>
			</p>
		</form>

		<script>
			$(document).ready(function() {

				if (!$("#id_plusone").is(":checked")) {
					$("#avec-table").hide();
					$("#id_avecbutton").hide();
					$("label[for=id_avecbutton]").hide();
				}

				$("#id_plusone").change(function() {
					$("#avec-table").toggle('slow');
					$("#id_avecbutton").toggle();
					$("label[for=id_avecbutton]").toggle();
				});
			});
		</script>

{% endblock %}

tf_arsfest/templates/sponsor_logos.html
<style>
@font-face {
    font-family: 'b2sq';
    src: url('/static/font/b2sq.ttf');
}
#spons {
	font-family: 'b2sq', sans-serif;
	font-weight: 400;
}

#spons img {
	max-width: 240px;
	max-height: 100px;
	margin: 50px;
}
#header {
	margin-top: 80px;
	font-size: 5.0em;
	color: #7A7AFF;
}
</style>
<div id="spons">
<center><h1 id="header">Årsfesten sponsras av</h2>

	<img src="{{ STATIC_URL }}festreklam/thermo14.jpg" alt="thermoscientific" />


	<img src="{{ STATIC_URL }}festreklam/ahola14.png" alt="Ahola" />


	<img src="{{ STATIC_URL }}festreklam/attracs14.png" alt="Attracs" />


	<img src="{{ STATIC_URL }}festreklam/futurice.png" alt="futurice" />


	<img src="{{ STATIC_URL }}festreklam/tfif14.png" alt="tfif" />


	<img src="{{ STATIC_URL }}festreklam/LR14.jpg" alt="Lloyd's Register" />
</center>
</div>